#!/bin/zsh

make

./9cc "${1}" > tmp.s

echo "\n----------------------------------------\n"
cat  tmp.s
echo "\n----------------------------------------\n"

cc -o tmp tmp.s
./tmp
output="$?"

echo "+--------+\n| result |  : ${output}\n+--------+"
